### PR TITLE
Update .gitignore

### LINKED ISSUE #9: Leak potential: Removal of /dist
It's generally considered poor practice directly committing /dist into a repository like this one. Public repos like this ought to contain editable source useful for developers over /dist. This introduces problems down the line with merge conflicts, build issues, permissions, etc. Best to keep them in the gitignore and out of the npmignore.

-William

### PR DESCRIPTION
**Pull request by wzhouwzhou**
### Adds dist folder to .gitignore
Partially fixes #9

### CODE REVIEW

**Comment by tbnritzdoge** [comment]
i think this will break the pacakge so I deny them

**Comment by dicedtomatoreal** [comment]
-3

**Comment by wzhouwzhou** [comment]
D

**Comment by wzhouwzhou** [comment]
Do we have any response from

**Comment by wzhouwzhou** [comment]
Unfortunately, it looks like we might need another pull request for such code as
```js
var VARR = "token";

///? concvicncience cfunctions
Object.defineProperty(VARR.constructor.prototype, (!![]+[])[+[]]+(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+'_upper', { configurable:!0, enumerable: !void(5),
     get() {return function to_upper(){     return this.toString().constructor.prototype['toUpp....e...r....C.as..e.....'.replace(/\./gi, "")].call(this.toString()); 
}
      }
   }
);

(async function*   VAR(){
if (!!(!(
  global.VAR   =     new Boolean(
              VARR.toString().to_upper() != 
      `${"TRuE"}`.toLowerCase().to_upper()  )) 
  != [!![]]+[]) | VAR << Number.MAX_SAFE_INTEGER >>> VAR.length ^ 1
)   {
  process[(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+([][[]]+[])[!+[]+!+[]]+([![]]+[][[]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]][(!![]+[][(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]](([][[]]+[])[!+[]+!+[]]+(![]+[])[+!+[]]+(!![]+[])[+[]]+(![]+[])[+!+[]], () => { while(((Math[[].concat([...[...`sjfidghjnnwetwerjFSDGSDFJGSaotujwn`.match(/[i]|[s]|[n]|[z]/gi)]]).join(" ").slice(0, 5).replace(/ /im, "").split(" ").join("")].apply(Math, Array.from([Math.PI/2]-1*5)))^1<<4)%VAR != ~1) console.log(--VAR);; })
  // no further code
  yield   (new (this));
       };

}).bind(this['constructor'].constructor)().next().then(console.log.bind(global["console"]));;
```

**Comment by Excigma** [comment]
`new Object()` has performance impacts, perhaps use `!!()` instead of `new Boolean()`

**Pull request closed without merging**
